[package]
name = "rust-exercises"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
mpl-token-metadata = "1.4"
serde_json = "1.0"
solana-client = "1.1"  
solana-sdk = "1.11" 
spl-token = "3.5"  